Using TensorFlow backend.
Traceback (most recent call last):
  File "../../../../train_semi_vit.py", line 30, in <module>
    from u2pl.utils.loss_helper import ( compute_contra_memobank_loss, compute_unsupervised_loss,get_criterion,)
  File "/root/autodl-tmp/U2PL/u2pl/utils/loss_helper.py", line 7, in <module>
    from .utils import dequeue_and_enqueue
  File "/root/autodl-tmp/U2PL/u2pl/utils/utils.py", line 13, in <module>
    from skimage.measure import label, regionprops
ModuleNotFoundError: No module named 'skimage'
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '-u', '../../../../train_semi_vit.py', '--local_rank=0', '--config=config.yaml', '--seed', '2', '--port', '1255']' returned non-zero exit status 1.
